#ifndef _DEFINE_H_
#define _DEFINE_H_

#define WINDOW_WIDTH 640
#define WINDOW_HEIGHT 480
#define WINDOW_TITLE "Evil Clutches"

#define ANIMATION_RATE 30.0f

#define SPRITE_PLAYER 0
#define SPRITE_BOSS 1
#define SPRITE_BACKGROUND 2
#define SPRITE_FIREBALL 3
#define SPRITE_DEMON 4
#define SPRITE_BABY_DRAGON 5

enum EntityTypeId
{
	ENTITY_TYPE_ID_PLAYER = 0,
	ENTITY_TYPE_ID_FIREBALL,
	ENTITY_TYPE_ID_BOSS,
	ENTITY_TYPE_ID_DEMON,
	ENTITY_TYPE_ID_BABY_DRAGON
};

enum SoundId
{
	SOUND_ID_MUSIC = 0,
	SOUND_ID_BABY,
	SOUND_ID_DEMON
};

#endif _DEFINE_H_